name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#       with:
#         fetch-depth: '0'
    - name: Fetch unshallow
      run: |
        git fetch --prune --tags --unshallow
        echo $(git tag -l)
        echo $(git describe --tags --always --first-parent)
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: gradle build
      run: ./gradlew build --info --stacktrace
    - name: gradle check
      run: ./gradlew check --info --stacktrace
