name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      fetch-depth: 0
    - name: Fetch unshallow
      run: git fetch --prune --tags --unshallow
    - name: Build
      run: ./gradlew build --info --stacktrace
    - name: Check
      run: ./gradlew check --info --stacktrace
