name: Release

on:
  release:
    types: [ created ]

jobs:
  release_cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch unshallow
      run: |
        git fetch --prune --tags --unshallow
        echo $(git describe --tags --always --first-parent)
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Install
      run: ./gradlew installDist --info --stacktrace
